### ISSUE TITLE
Termux android

### ISSUE THREAD

**Issue by arsemor** [therealtear/discord-nitro-generator#45]
When i try run app i see this error
$ node app.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/data/data/com.termux/files/home/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack:

Commands what i write
pkg install git
pkg install nodejs
git https://github.com/therealtear/discord-nitro-generator
npm install
node app.js

**Comment by therealtear** [comment]
CD to the folder and type “npm i”
