### ISSUE TITLE
cant run it?!?!

### ISSUE THREAD

**Issue by pjmangaming** [therealtear/discord-nitro-generator#49]
heres the error:

                        generic: process.env.TERM.toLowerCase() ,
                                                  ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.get [as terminal] (C:\Users\pp\Desktop\discord-nitro-generator-main\discord-nitro-generator-main\node_modules\terminal-kit\lib\termkit.js:350:30)
    at Object.<anonymous> (C:\Users\pp\Desktop\discord-nitro-generator-main\discord-nitro-generator-main\app.js:8:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by therealtear** [comment]
Yea that’s not an issue with the code lol thay isn’t even in the code anywhere

**Comment by pjmangaming** [comment]
how should i fix it then?

**Comment by therealtear** [comment]
Redownload latest version of the code and follow all the steps in the readme
